"""initial

Revision ID: 2adcbd4b367a
Revises:
Create Date: 2026-07-24 12:19:11.504337
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # PATCH 2: autogenerate does not pick up Sequence objects attached to a
    # column. Without this, every INSERT into signals fails at runtime.
    op.execute("CREATE SEQUENCE IF NOT EXISTS signal_chain_seq START 1 INCREMENT 1")

    op.create_table(
        "excerpts",
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("archive_url", sa.Text(), nullable=True),
        sa.Column("source_domain", sa.String(length=255), nullable=False),
        sa.Column("source_title", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "char_count = char_length(text)",
            name=op.f("ck_excerpts_char_count_matches"),
        ),
        sa.CheckConstraint(
            "char_length(text) <= 500", name=op.f("ck_excerpts_excerpt_length_cap")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_excerpts")),
    )
    op.create_index(
        "ix_excerpts_content_sha", "excerpts", ["content_sha256"], unique=False
    )
    op.create_index(
        op.f("ix_excerpts_created_at"), "excerpts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_excerpts_source_domain"), "excerpts", ["source_domain"], unique=False
    )
    op.create_table(
        "orgs",
        sa.Column("clerk_org_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("home_country", sa.String(length=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orgs")),
        sa.UniqueConstraint("clerk_org_id", name=op.f("uq_orgs_clerk_org_id")),
    )
    op.create_index(op.f("ix_orgs_created_at"), "orgs", ["created_at"], unique=False)
    op.create_table(
        "shredded_fields",
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("subject_ref", sa.String(length=64), nullable=False),
        sa.Column("field_name", sa.String(length=64), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shredded_fields")),
    )
    op.create_index(
        op.f("ix_shredded_fields_created_at"),
        "shredded_fields",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shredded_fields_signal_id"),
        "shredded_fields",
        ["signal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shredded_fields_subject_ref"),
        "shredded_fields",
        ["subject_ref"],
        unique=False,
    )
    op.create_table(
        "subject_keys",
        sa.Column("subject_ref", sa.String(length=64), nullable=False),
        sa.Column("wrapped_key", sa.LargeBinary(), nullable=False),
        sa.Column("wrap_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("erased_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subject_keys")),
        sa.UniqueConstraint("subject_ref", name=op.f("uq_subject_keys_subject_ref")),
    )
    op.create_index(
        op.f("ix_subject_keys_created_at"), "subject_keys", ["created_at"], unique=False
    )
    op.create_index(
        "ix_subject_keys_ref", "subject_keys", ["subject_ref"], unique=False
    )
    op.create_table(
        "audit_log",
        sa.Column(
            "action",
            sa.Enum(
                "VENDOR_CREATED",
                "VENDOR_UPDATED",
                "VENDOR_DEACTIVATED",
                "CAPTURE_RUN",
                "SIGNAL_INSERTED",
                "SIGNAL_DISPUTED",
                "SCORE_COMPUTED",
                "ALERT_FIRED",
                "ALERT_ACKNOWLEDGED",
                "ARTIFACT_GENERATED",
                "CONTRACT_UPDATED",
                "REGISTER_EXPORTED",
                "PDF_EXPORTED",
                "CHAIN_VERIFIED",
                "ERASURE_REQUESTED",
                "ERASURE_EXECUTED",
                "CALIBRATION_LOADED",
                name="audit_action",
            ),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("actor_email", sa.String(length=255), nullable=True),
        sa.Column("actor_ip", postgresql.INET(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("payload_hash", sa.String(length=64), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_audit_log_org_id_orgs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_actor"), "audit_log", ["actor"], unique=False)
    op.create_index(
        op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False
    )
    op.create_index(
        "ix_audit_log_entity", "audit_log", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_entity_id"), "audit_log", ["entity_id"], unique=False
    )
    op.create_index(
        "ix_audit_log_org_created", "audit_log", ["org_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_log_org_id"), "audit_log", ["org_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("clerk_user_id", sa.String(length=128), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "ANALYST", "VIEWER", name="org_role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_users_org_id_orgs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("clerk_user_id", name=op.f("uq_users_clerk_user_id")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
    op.create_table(
        "vendors",
        sa.Column("lei", sa.String(length=20), nullable=True),
        sa.Column("legal_name", sa.String(length=512), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("aliases", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column(
            "negative_terms", sa.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "entity_type",
            sa.Enum(
                "PUBLIC_US",
                "PUBLIC_EU",
                "PRIVATE",
                "SUBSIDIARY",
                "GOVERNMENT",
                "UNKNOWN",
                name="entity_type",
            ),
            nullable=False,
        ),
        sa.Column("cik", sa.String(length=10), nullable=True),
        sa.Column("ticker", sa.String(length=16), nullable=True),
        sa.Column("companies_house_number", sa.String(length=16), nullable=True),
        sa.Column("crunchbase_uuid", sa.String(length=64), nullable=True),
        sa.Column("primary_domain", sa.String(length=255), nullable=True),
        sa.Column("careers_url", sa.Text(), nullable=True),
        sa.Column("parent_lei", sa.String(length=20), nullable=True),
        sa.Column("ultimate_parent_lei", sa.String(length=20), nullable=True),
        sa.Column("successor_lei", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_critical", sa.Boolean(), nullable=False),
        sa.Column("capture_enabled", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("last_capture_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_capture_ok", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "cik IS NULL OR cik ~ '^[0-9]{1,10}$'", name=op.f("ck_vendors_cik_format")
        ),
        sa.CheckConstraint(
            "lei IS NULL OR lei ~ '^[A-Z0-9]{20}$'", name=op.f("ck_vendors_lei_format")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_vendors_org_id_orgs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
    )
    op.create_index(op.f("ix_vendors_cik"), "vendors", ["cik"], unique=False)
    op.create_index(
        op.f("ix_vendors_created_at"), "vendors", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_vendors_lei"), "vendors", ["lei"], unique=True)
    op.create_index(
        "ix_vendors_org_active", "vendors", ["org_id", "is_active"], unique=False
    )
    op.create_index(op.f("ix_vendors_org_id"), "vendors", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_vendors_parent_lei"), "vendors", ["parent_lei"], unique=False
    )
    op.create_index(
        op.f("ix_vendors_ultimate_parent_lei"),
        "vendors",
        ["ultimate_parent_lei"],
        unique=False,
    )
    op.create_table(
        "contracts",
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("contractual_arrangement_ref", sa.String(length=128), nullable=False),
        sa.Column("provider_lei", sa.String(length=20), nullable=True),
        sa.Column("provider_legal_name", sa.String(length=512), nullable=False),
        sa.Column("provider_country", sa.String(length=2), nullable=True),
        sa.Column("function_identifier", sa.String(length=64), nullable=True),
        sa.Column("function_name", sa.Text(), nullable=True),
        sa.Column("ict_service_type", sa.String(length=128), nullable=True),
        sa.Column("supports_critical_function", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("notice_period_days", sa.Integer(), nullable=True),
        sa.Column("governing_law_country", sa.String(length=2), nullable=True),
        sa.Column("annual_cost_eur", sa.Integer(), nullable=True),
        sa.Column(
            "data_location_countries",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "processing_location_countries",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("sensitive_data_involved", sa.Boolean(), nullable=False),
        sa.Column(
            "subcontractors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "substitutability",
            sa.Enum(
                "NOT_SUBSTITUTABLE",
                "HIGHLY_COMPLEX",
                "MEDIUM_COMPLEX",
                "EASILY_SUBSTITUTABLE",
                name="substitutability_rating",
            ),
            nullable=True,
        ),
        sa.Column("exit_plan_exists", sa.Boolean(), nullable=False),
        sa.Column("exit_plan_last_tested", sa.Date(), nullable=True),
        sa.Column("reintegration_possible", sa.Boolean(), nullable=True),
        sa.Column("register_version", sa.Integer(), nullable=False),
        sa.Column("last_reviewed_by", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "provider_country IS NULL OR provider_country ~ '^[A-Z]{2}$'",
            name=op.f("ck_contracts_provider_country_iso"),
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name=op.f("ck_contracts_contract_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_contracts_org_id_orgs")
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendors.id"], name=op.f("fk_contracts_vendor_id_vendors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contracts")),
        sa.UniqueConstraint("vendor_id", name=op.f("uq_contracts_vendor_id")),
    )
    op.create_index(
        op.f("ix_contracts_created_at"), "contracts", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_contracts_org_id"), "contracts", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_contracts_provider_lei"), "contracts", ["provider_lei"], unique=False
    )
    op.create_table(
        "org_vendor_access",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_org_vendor_access_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_org_vendor_access_vendor_id_vendors"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_vendor_access")),
        sa.UniqueConstraint("user_id", "vendor_id", name="uq_user_vendor_access"),
    )
    op.create_index(
        op.f("ix_org_vendor_access_created_at"),
        "org_vendor_access",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_org_vendor_access_user_id"),
        "org_vendor_access",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_org_vendor_access_vendor", "org_vendor_access", ["vendor_id"], unique=False
    )
    op.create_index(
        op.f("ix_org_vendor_access_vendor_id"),
        "org_vendor_access",
        ["vendor_id"],
        unique=False,
    )
    op.create_table(
        "signals",
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column(
            "metric",
            sa.Enum(
                "LEADERSHIP_CHANGE",
                "LEGAL_EVENT",
                "HEADCOUNT_CHANGE",
                "SENTIMENT",
                "NEWS_VOLUME",
                "OPEN_ROLES",
                "FUNDING_EVENT",
                "REGULATORY_FILING",
                name="signal_metric",
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "BRIGHTDATA_MCP",
                "SEC_EDGAR",
                "SEC_FORM_D",
                "COURTLISTENER",
                "COMPANIES_HOUSE",
                "CRUNCHBASE",
                "GDELT",
                "GLEIF",
                "MANUAL",
                name="signal_source",
            ),
            nullable=False,
        ),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("excerpt_id", sa.UUID(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("archive_url", sa.Text(), nullable=True),
        sa.Column("validator_verdict", sa.String(length=16), nullable=False),
        sa.Column("validator_confidence", sa.Float(), nullable=True),
        sa.Column("validator_model_id", sa.String(length=64), nullable=True),
        sa.Column("validator_prompt_hash", sa.String(length=64), nullable=True),
        sa.Column("dedup_key", sa.String(length=64), nullable=False),
        sa.Column("chain_seq", sa.BigInteger(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "prev_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_signals_prev_hash_format")
        ),
        sa.CheckConstraint(
            "row_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_signals_row_hash_format")
        ),
        sa.CheckConstraint(
            "validator_verdict IN ('accepted','rejected','unreviewed')",
            name=op.f("ck_signals_validator_verdict_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["excerpt_id"], ["excerpts.id"], name=op.f("fk_signals_excerpt_id_excerpts")
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendors.id"], name=op.f("fk_signals_vendor_id_vendors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
        sa.UniqueConstraint("chain_seq", name=op.f("uq_signals_chain_seq")),
        sa.UniqueConstraint("dedup_key", name="uq_signals_dedup_key"),
        sa.UniqueConstraint("row_hash", name=op.f("uq_signals_row_hash")),
    )
    op.create_index("ix_signals_chain_seq", "signals", ["chain_seq"], unique=False)
    op.create_index(
        op.f("ix_signals_created_at"), "signals", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_signals_event_date"), "signals", ["event_date"], unique=False
    )
    op.create_index(
        op.f("ix_signals_excerpt_id"), "signals", ["excerpt_id"], unique=False
    )
    op.create_index(
        op.f("ix_signals_observed_at"), "signals", ["observed_at"], unique=False
    )
    op.create_index(
        op.f("ix_signals_vendor_id"), "signals", ["vendor_id"], unique=False
    )
    op.create_index(
        "ix_signals_vendor_metric_observed",
        "signals",
        ["vendor_id", "metric", "observed_at"],
        unique=False,
    )

    # PATCH 2 (cont): bind the sequence to signals.chain_seq so inserts that
    # omit the column get the next value automatically.
    op.execute("ALTER SEQUENCE signal_chain_seq OWNED BY signals.chain_seq")
    op.execute(
        "ALTER TABLE signals ALTER COLUMN chain_seq SET DEFAULT nextval('signal_chain_seq')"
    )

    op.create_table(
        "vendor_scores",
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("composite", sa.Float(), nullable=False),
        sa.Column("previous_composite", sa.Float(), nullable=True),
        sa.Column("delta", sa.Float(), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("weights_version", sa.String(length=32), nullable=False),
        sa.Column("thresholds_version", sa.String(length=32), nullable=False),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column(
            "excluded_signal_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "composite >= 0 AND composite <= 100",
            name=op.f("ck_vendor_scores_composite_range"),
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_scores_vendor_id_vendors"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_scores")),
    )
    op.create_index(
        op.f("ix_vendor_scores_computed_at"),
        "vendor_scores",
        ["computed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_scores_created_at"),
        "vendor_scores",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_vendor_scores_vendor_computed",
        "vendor_scores",
        ["vendor_id", "computed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_scores_vendor_id"), "vendor_scores", ["vendor_id"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("vendor_score_id", sa.UUID(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("WATCH", "ELEVATED", "CRITICAL", name="alert_severity"),
            nullable=False,
        ),
        sa.Column("fired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "converged_dimensions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("dimension_count", sa.Integer(), nullable=False),
        sa.Column("convergence_score", sa.Float(), nullable=False),
        sa.Column("threshold_value", sa.Float(), nullable=False),
        sa.Column("thresholds_version", sa.String(length=32), nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "notify_channels",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.String(length=128), nullable=True),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendors.id"], name=op.f("fk_alerts_vendor_id_vendors")
        ),
        sa.ForeignKeyConstraint(
            ["vendor_score_id"],
            ["vendor_scores.id"],
            name=op.f("fk_alerts_vendor_score_id_vendor_scores"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(
        op.f("ix_alerts_created_at"), "alerts", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_alerts_fired_at"), "alerts", ["fired_at"], unique=False)
    op.create_index("ix_alerts_open", "alerts", ["is_open", "fired_at"], unique=False)
    op.create_index(
        "ix_alerts_vendor_fired", "alerts", ["vendor_id", "fired_at"], unique=False
    )
    op.create_index(op.f("ix_alerts_vendor_id"), "alerts", ["vendor_id"], unique=False)
    op.create_table(
        "corrections",
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("superseded_by_signal_id", sa.UUID(), nullable=True),
        sa.Column(
            "reason",
            sa.Enum(
                "WRONG_ENTITY",
                "FACTUALLY_INCORRECT",
                "DUPLICATE",
                "STALE",
                "MISCLASSIFIED",
                "VENDOR_DISPUTED",
                "OTHER",
                name="correction_reason",
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("actor_email", sa.String(length=255), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("score_before", sa.Float(), nullable=True),
        sa.Column("score_after", sa.Float(), nullable=True),
        sa.Column("recomputed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_corrections_org_id_orgs")
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"], ["signals.id"], name=op.f("fk_corrections_signal_id_signals")
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_signal_id"],
            ["signals.id"],
            name=op.f("fk_corrections_superseded_by_signal_id_signals"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corrections")),
        sa.UniqueConstraint("signal_id", name="uq_corrections_signal"),
    )
    op.create_index(
        op.f("ix_corrections_created_at"), "corrections", ["created_at"], unique=False
    )
    op.create_index(
        "ix_corrections_org_created",
        "corrections",
        ["org_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_corrections_signal_id"), "corrections", ["signal_id"], unique=False
    )
    op.create_table(
        "dimension_scores",
        sa.Column("vendor_score_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        # PATCH 3: signal_metric already created by the signals table above.
        # create_type=False stops Postgres erroring with "type already exists".
        sa.Column(
            "dimension",
            postgresql.ENUM(name="signal_metric", create_type=False),
            nullable=False,
        ),
        sa.Column("raw_value", sa.Float(), nullable=True),
        sa.Column("baseline", sa.Float(), nullable=True),
        sa.Column("z_score", sa.Float(), nullable=True),
        sa.Column("anomaly_ratio", sa.Float(), nullable=True),
        sa.Column("contribution", sa.Float(), nullable=False),
        sa.Column("weight_applied", sa.Float(), nullable=False),
        sa.Column(
            "context_conditioned", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "confidence",
            sa.Enum("VERIFIED", "REPORTED", "UNCONFIRMED", name="confidence_tier"),
            nullable=False,
        ),
        sa.Column(
            "signal_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_dimension_scores_vendor_id_vendors"),
        ),
        sa.ForeignKeyConstraint(
            ["vendor_score_id"],
            ["vendor_scores.id"],
            name=op.f("fk_dimension_scores_vendor_score_id_vendor_scores"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dimension_scores")),
    )
    op.create_index(
        op.f("ix_dimension_scores_created_at"),
        "dimension_scores",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_dimension_scores_vendor_dim",
        "dimension_scores",
        ["vendor_id", "dimension", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dimension_scores_vendor_id"),
        "dimension_scores",
        ["vendor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dimension_scores_vendor_score_id"),
        "dimension_scores",
        ["vendor_score_id"],
        unique=False,
    )
    op.create_table(
        "narrative_artifacts",
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("vendor_score_id", sa.UUID(), nullable=True),
        sa.Column("narrative_md", sa.Text(), nullable=False),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("prompt_name", sa.String(length=64), nullable=False),
        sa.Column(
            "input_signal_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("citation_resolution_pct", sa.Float(), nullable=True),
        sa.Column("distinct_claims", sa.Integer(), nullable=True),
        sa.Column("distinct_citations", sa.Integer(), nullable=True),
        sa.Column("unresolved_count", sa.Integer(), nullable=True),
        sa.Column("entailment_fidelity_pct", sa.Float(), nullable=True),
        sa.Column("entailment_sampled", sa.Integer(), nullable=True),
        sa.Column("entailment_failed", sa.Integer(), nullable=True),
        sa.Column("is_fallback", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_narrative_artifacts_content_hash_format"),
        ),
        sa.CheckConstraint(
            "prompt_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_narrative_artifacts_prompt_hash_format"),
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_narrative_artifacts_vendor_id_vendors"),
        ),
        sa.ForeignKeyConstraint(
            ["vendor_score_id"],
            ["vendor_scores.id"],
            name=op.f("fk_narrative_artifacts_vendor_score_id_vendor_scores"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_narrative_artifacts")),
        # PATCH 4: duplicate UNIQUE on content_hash removed. One constraint only.
        sa.UniqueConstraint("content_hash", name="uq_artifacts_content_hash"),
    )
    op.create_index(
        "ix_artifacts_vendor_generated",
        "narrative_artifacts",
        ["vendor_id", "generated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_narrative_artifacts_created_at"),
        "narrative_artifacts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_narrative_artifacts_vendor_id"),
        "narrative_artifacts",
        ["vendor_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_narrative_artifacts_vendor_id"), table_name="narrative_artifacts"
    )
    op.drop_index(
        op.f("ix_narrative_artifacts_created_at"), table_name="narrative_artifacts"
    )
    op.drop_index("ix_artifacts_vendor_generated", table_name="narrative_artifacts")
    op.drop_table("narrative_artifacts")
    op.drop_index(
        op.f("ix_dimension_scores_vendor_score_id"), table_name="dimension_scores"
    )
    op.drop_index(op.f("ix_dimension_scores_vendor_id"), table_name="dimension_scores")
    op.drop_index("ix_dimension_scores_vendor_dim", table_name="dimension_scores")
    op.drop_index(op.f("ix_dimension_scores_created_at"), table_name="dimension_scores")
    op.drop_table("dimension_scores")
    op.drop_index(op.f("ix_corrections_signal_id"), table_name="corrections")
    op.drop_index("ix_corrections_org_created", table_name="corrections")
    op.drop_index(op.f("ix_corrections_created_at"), table_name="corrections")
    op.drop_table("corrections")
    op.drop_index(op.f("ix_alerts_vendor_id"), table_name="alerts")
    op.drop_index("ix_alerts_vendor_fired", table_name="alerts")
    op.drop_index("ix_alerts_open", table_name="alerts")
    op.drop_index(op.f("ix_alerts_fired_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_created_at"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_vendor_scores_vendor_id"), table_name="vendor_scores")
    op.drop_index("ix_vendor_scores_vendor_computed", table_name="vendor_scores")
    op.drop_index(op.f("ix_vendor_scores_created_at"), table_name="vendor_scores")
    op.drop_index(op.f("ix_vendor_scores_computed_at"), table_name="vendor_scores")
    op.drop_table("vendor_scores")
    op.drop_index("ix_signals_vendor_metric_observed", table_name="signals")
    op.drop_index(op.f("ix_signals_vendor_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_observed_at"), table_name="signals")
    op.drop_index(op.f("ix_signals_excerpt_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_event_date"), table_name="signals")
    op.drop_index(op.f("ix_signals_created_at"), table_name="signals")
    op.drop_index("ix_signals_chain_seq", table_name="signals")
    op.drop_table("signals")
    op.drop_index(
        op.f("ix_org_vendor_access_vendor_id"), table_name="org_vendor_access"
    )
    op.drop_index("ix_org_vendor_access_vendor", table_name="org_vendor_access")
    op.drop_index(op.f("ix_org_vendor_access_user_id"), table_name="org_vendor_access")
    op.drop_index(
        op.f("ix_org_vendor_access_created_at"), table_name="org_vendor_access"
    )
    op.drop_table("org_vendor_access")
    op.drop_index(op.f("ix_contracts_provider_lei"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_org_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_created_at"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_index(op.f("ix_vendors_ultimate_parent_lei"), table_name="vendors")
    op.drop_index(op.f("ix_vendors_parent_lei"), table_name="vendors")
    op.drop_index(op.f("ix_vendors_org_id"), table_name="vendors")
    op.drop_index("ix_vendors_org_active", table_name="vendors")
    op.drop_index(op.f("ix_vendors_lei"), table_name="vendors")
    op.drop_index(op.f("ix_vendors_created_at"), table_name="vendors")
    op.drop_index(op.f("ix_vendors_cik"), table_name="vendors")
    op.drop_table("vendors")
    op.drop_index(op.f("ix_users_org_id"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_audit_log_org_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_org_created", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_entity_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_entity", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("ix_subject_keys_ref", table_name="subject_keys")
    op.drop_index(op.f("ix_subject_keys_created_at"), table_name="subject_keys")
    op.drop_table("subject_keys")
    op.drop_index(op.f("ix_shredded_fields_subject_ref"), table_name="shredded_fields")
    op.drop_index(op.f("ix_shredded_fields_signal_id"), table_name="shredded_fields")
    op.drop_index(op.f("ix_shredded_fields_created_at"), table_name="shredded_fields")
    op.drop_table("shredded_fields")
    op.drop_index(op.f("ix_orgs_created_at"), table_name="orgs")
    op.drop_table("orgs")
    op.drop_index(op.f("ix_excerpts_source_domain"), table_name="excerpts")
    op.drop_index(op.f("ix_excerpts_created_at"), table_name="excerpts")
    op.drop_index("ix_excerpts_content_sha", table_name="excerpts")
    op.drop_table("excerpts")

    # PATCH 2: drop the sequence.
    op.execute("DROP SEQUENCE IF EXISTS signal_chain_seq")

    # Autogenerate does not drop enum TYPEs, only the tables using them.
    # Without these, re-running upgrade after a downgrade fails with
    # "type already exists".
    for enum_name in (
        "signal_metric",
        "signal_source",
        "audit_action",
        "org_role",
        "entity_type",
        "substitutability_rating",
        "alert_severity",
        "correction_reason",
        "confidence_tier",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
